const ERROR_FETCHING_FROM_API = 'ERROR_FETCHING_FROM_API';
const ERROR_INSERTING_NEWS = 'ERROR_INSERTING_NEWS';
const ERROR_NEW_NOT_EXIST = 'ERROR_NEW_NOT_EXIST';
const ERROR_REMOVING_NEWS = "ERROR_REMOVING_NEWS";

module.exports = {
  ERROR_FETCHING_FROM_API,
  ERROR_INSERTING_NEWS,
  ERROR_NEW_NOT_EXIST,
  ERROR_REMOVING_NEWS,
};