const ERROR_FETCHING_FROM_API = 'ERROR_FETCHING_FROM_API';
const ERROR_INSERTING_NEWS = 'ERROR_INSERTING_NEWS';
const ERROR_NEW_NOT_EXIST = 'ERROR_NEW_NOT_EXIST';

module.exports = {
  ERROR_FETCHING_FROM_API,
  ERROR_INSERTING_NEWS,
  ERROR_NEW_NOT_EXIST,
};